---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 768

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.17.44

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[fake]
    attributes:
